# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m venv .space_backend
        source .space_backend/bin/activate
        pip install --upgrade pip
        pip install -r src/BackEnd/fundamentos/requierments.txt
    - name: build with uvicorn
      run: |
        source .space_backend/bin/activate
        uvicorn src.BackEnd.fundamentos.main:app --reload --port 3000
        
